### ISSUE TITLE
Specify connectors to ASR vendors

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#109]
Define the requirements for building connectors to:
- AWS Transcribe
- Google Speech
- IBM Watson
- Speechmatics

**Comment by amessina71** [comment]
I propose to add Microsoft Speech Engine

**Comment by EyalLavi** [comment]
Work is also ongoing for Bertin IT and Vocalia.

**Comment by EyalLavi** [comment]
Wiki page to collect the information: https://github.com/ebu/benchmarkstt/wiki/Vendor-connectors

**Comment by EyalLavi** [comment]
In the meeting today it was argued that connectors are valuable in their own right and that they should be decoupled from BenchmarkSTT and have their own repo. In this scenario, we will not specify how to write the connectors. Instead, each connector will pass transcript file(s) into BenchmarkSTT. The task in this case will be to ensure that BenchmarkSTT can be plugged into end-to-end workflows. For example, each connector will have to create a plain text version of the transcript (the current release of BenchmarkSTT takes plain text only).

As an interim solution, we will gather data on existing production practices and come up with a suggested workflow (which may well be manual). Once a common workflow is established, we will consider consolidating it into code.

**Comment by EyalLavi** [comment]
This repo has connectors for Amazon Lex, Google, Google Cloud, Houndify, IBM Watson, Microsoft (a.k.a. Bing), Speechmatics and Wit: https://github.com/Franck-Dernoncourt/ASR_benchmark/blob/master/src/settings.ini

**Comment by EyalLavi** [comment]
SRF make a good argument for only including in this tool the conversion from vendor output to BenchmarkSTT input (in this release, plain text). This has the following benefits:
- Reduced scope for BenchmarkSTT 
- Avoids duplication of effort (the repo linked above)
- No need to maintain a separate repo.

In this case, rather than 'connectors' we implement 'converters'.

**Comment by EyalLavi** [comment]
Decision today:
1. Connectors to vendor APIs and any UI will be in a separate repo that will reference BenchmarkSTT.
2. Conversion from vendor output to BenchmarkSTT input (in this release, convert to plain text): for this release, we only specify plain text as input and provide some guidance in the documentation. In future releases when we need a more structured transcript format we will come back to the question of whether the conversion is in scope. 
3. FTV to add some description of their work for interested users. 
4. @danielthepope will review FTV repo
5. API of BenchmarkSTT will be part of release 1. Looking for resource to review code and determine test coverage. Make ticket.

**Comment by EyalLavi** [comment]
The connectors and converters are out of scope for this repo so I'm closing this issue.
