### ISSUE TITLE
Regex normalisation rules

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#11]
We agreed that for v1, normalisation will be based on simple replacement pairs, one table per language. Many of these pairs will follow a pattern, for example `well-liked`:`well liked`, `well-known`:`well known`. These can be replaced with a regex pattern: `([a-zA-Z]+)\-([a-zA-Z]+)`:`$1\s$2`.

The proposal is for the normaliser to consume a regex pattern file per language in addition to the simple replacement table. 

To be decided if this is in scope for v1.

**Comment by amessina71** [comment]
I would vote for this to be in scope of v1. I have been thinking about the same issue in Italian. For example "grande caldo" -> "gran caldo", "grande problema" ->"gran problema", but "grande ala" -> "grande ala" , i.e. you can truncate "de" of "grande" only if the follwoing word does not start with a vowel (can't transalte this into regex syntax though ... help).

**Comment by MikeSmithEU** [comment]
I've added this functionality as a normaliser in #13 

I've done a quick doctest with this file: 
https://github.com/ebu/ai-benchmarking-stt/blob/c74f72a46a9eb3778a62b45904c1235266fed6a3/resources/normalisers/test/regexreplace/en_US

**Comment by MikeSmithEU** [comment]
> can't transalte this into regex syntax though ... help

@amessina71

That would be `(gran)de(?=\s+[b-df-hj-np-tv-z])` to be replaced by `\1`, or in the csv file it would thus correspond to the line

`(gran)de(?=\s+[b-df-hj-np-tv-z]),\1`

I've added this example in the test code `/resources/normalisers/test/regexreplace/it` of Pull Request #13

**Comment by EyalLavi** [comment]
Rules operate from top to bottom. So if `1` is replaced by `one`, a later rule to replace `21` will not be applied. This will also apply to regex. Rules may conflict/override. 

Log which rules were applied? Show this in the results matrix.

Make sure complexities are documented in the code.

Keep rules types separate and modular so that each use case can use a different set. 

Agreed in Webex today to include simple rules and regex only in v1. For specific issues we will raise other tickets.

**Comment by MikeSmithEU** [comment]
> Log which rules were applied? Show this in the results matrix.

Logging now implemented in #19
