### ISSUE TITLE
Prepare API for release

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#112]
Originally, the API and its Explorer were considered helpers: https://benchmarkstt.readthedocs.io/en/latest/api.html. The group decided to make them part of the official release, so the code needs to be reviewed and tested.

**Comment by EyalLavi** [comment]
Summarising investigation with @danielthepope : 
- API Methods are created from the classes used by BenchmarkSTT core, so they are tested.
- Explorer HTML is hand-written, we would rather not touch it, but it seems to work.
- UI pulls data from the code, so should also be fine. 
In summary, we don't think there's much more work to do so we can remove the warning in the docs and make it part of the official release. 
@danielthepope will check over things just in case.

**Comment by danielthepope** [comment]
Checked this over and I think it's fine 👍
