### ISSUE TITLE
Metric: Named entity recognition EditNew Page

### ISSUE THREAD

**Issue by aro-max** [ebu/benchmarkstt#115]
### Computation of the Named Entity Error Rate, (NEER) 

First, we can envisage to perform a preprocessing and then call the command line benchmarkstt. 
It has to be noticed that with this approach, the Named Entity, NE,  and the files have to be normalized with the same rules. The preprocessing step consists in detecting a list of NEs and replacing each word that is not a NE by a constant word, ‘x’ for instance. 
The code corresponding to this experiment is published in:
_branch experiment-not-for-merging_ : studies/neer/study_neer.py 

### Method 1 :  Processing steps 

1. Normalise the named entities with the same rules than the document
2. Find all the occurrence of each named entity
3. Replace each word in the document that is not a NE by x
4. Compute the WER on the resulting file containing only NEs and ‘x’

**Exemple :**
Following the tutorial : 
https://benchmarkstt.readthedocs.io/en/latest/tutorial.html#word-error-rate-and-normalization
We generate the normalized files:

benchmarkstt-tools normalization -i qt_reference.txt -o qt_reference_normalized.txt --lowercase --regex "[,.-]" " "
benchmarkstt-tools normalization -i qt_kaldi_hypothesis.txt -o qt_kaldi_hypothesis_normalized.txt --lowercase --regex "[,.-]" " "

We obtained two files as explained in the tutorial:
qt_reference.txt
qt_kaldi_hypothesis.txt

Let’s consider that the NEs are defined as a list : 
named_entities = ["minister","theresa may"] 

For the sake of readability only the first 200 words of the text files are kept. We apply the processing of method 1. The resulting files of the step 3 are:

**_reference_x.txt_**
x x x x x x minister theresa may x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x minister theresa may x x x x x x x x x x x x minister x x x x x x x x x x
**_hypothesis_x.txt_**
x x x minister theresa may x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x minister theresa may x x minister x x x x x x x x x x x x x x x x x x x x x x x x x x
We then compute the WER, step 4 with the cli:
benchmarkstt --reference reference_x.txt --hypothesis hypothesis_x.txt --wer --diffcounts
It gives  : 

**wer**
0.160000

**diffcounts**
equal: 184
replace: 0
insert: 16
delete: 16

It we exclude the x from the input files, there is a perfect match on the NE.
minister, theresa may, minister, theresa may, minister

**Conclusion method 1 :** 

The WER computed after the preprocessing is not null whereas there’s a perfect match of detected NE. The errors that are not on NEs leak on the WER, the algorithms is not able the re-aligned the two texts.
To have a NEER that only depends on NEs we consider the mesure of the difference of two bags of words extracted from the reference text and the hypothesis text.

### Method 2:

To avoid the errors leakage we consider using only the set of extracted NEs. Then the metric is directly computed on the set of NEs. We investigated two options to compute the NEER.

The first one consists in constructing a text with the NEs to generate an ordered list. Then the benchmarkstt  command is used to compute the WER. The advantage of this method is to separate the computation of the WER and the extraction of the NEs. The drawback is the explainability of the results.

### Method 2 A :  Processing steps 

1. Find all the occurrence of each named entity, it does not required normalization
2. Build a file containing the ordered NEs 
3. Compute the WER on the resulting files containing all the ordered NEs 

**Exemple :** 
To illustrate the two methods we introduce an error in both files.

**Outputs of step A :**
reference_ne.txt = 'minister theresa may minister theresa may minister'
hypothesis_ne.txt = 'minister minister minister theresa may'

benchmarkstt --reference reference_ne.txt --hypothesis hypothesis_ne.txt --wer --diffcounts

**wer**
0.857143

**diffcounts**
equal: 3
replace: 0
insert: 2
delete: 4

**Conclusion method 2 A:** 

The main issue is that the WER on named entity is not easy to explain as the text is a mixture of named entities. On option would be to call the command line on separately extracted NEs. In that case the WER becomes a simple word count, but the computation complexity is not very efficient.
 
The second option consists in developing a separate metric for NEs.

### Method 2 B :  Processing steps 

1. Find all the occurrence of each named entity, it does not required normalization
2. Build a file containing all the NEs 
3. Compute the NEER for each NE with the following formula
           neer[entity] = abs(count_ref-count_hypothesis)/count_ref

count_ref = the number of occurrence of NE ‘entity’ in the reference file
count_hypothesis = the number of occurrence of NE ‘entity’ in the hypothesis file 
abs() = absolute value

**Exemple :** 
We introduce errors in the extracted NE for the sake of explainability.

reference_ne.txt = 'minister theresa may minister theresa may minister'
hypothesis_ne.txt = 'minister minister minister theresa may’

Call of the function not yet integrated in cli.

neer_bag( named_entities, list_hypthesis_ne, list_reference_ne )

>> {'minister': 0.0, 'theresa may': 0.5, 'av_neer': 0.2}

The output of the neer_bag() is a dictionary of NEER for each entity. The average NEER av_neer corresponds to the NEER considering all the NE as identical.

**Next step :** 

We can define a dictionary of NEER and not a list. 
For instance:
**Input:** 
>{‘noon’ :  [‘minister’,’theresa may’],
‘verb’ :  [‘sold ‘,'done’],
}

**Output :**
>{‘noon’: [ {’minister’: 0.0, 'theresa may': 0.5, 'av_neer': 0.2}],
‘verb’:  [ {‘sold’ : 0.0 , ‘done’ : 0.2 , 'av_neer': 0.1}] 
}

**Comment by EyalLavi** [comment]
@alexandre-rouxel would you expect the results to be different when using the revised Levenshtein metric implemented in #114?

**Comment by AmelMhamdi** [comment]
The writing team does not need to detect the named entities, however they do need a transcript as close as possible to the audio. where they only need WER. on the other hand the team responsible for indexing they rather need named entities. after merging the named entity detection in the WER calculation can be useful to give more precision but sometimes they only need to detect the named entity with a time code.


hence the need to split the NEER calculation and create a metric for entity detection named with time code precision.

**Comment by EyalLavi** [comment]
In meeting today:
- Position of NE is required in the transcript, not in the output of BenchmarkSTT
- Return list of NEs with error rate as dictionary. 
- Add average at the end of the dictionary.
- Show summary of results "minister 3/4; Theresa May 0/2"
- @AmelMhamdi to provide use case for scoring timing information in addition to recognition.
