### ISSUE TITLE
Restore build instructions

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#118]
In the docs, we used to have a section for building from the repo. It's been replaced by the pypi recommended method, but it would still be good to have the other option in the installation document for local dev.

**Comment by MikeSmithEU** [comment]
Isn’t https://benchmarkstt.readthedocs.io/en/latest/development.html what you are looking for? We could/should link to the development page from the installation page as well...

**Comment by EyalLavi** [comment]
That's exactly it! Thanks @MikeSmithEU. I'll add a link to the docs.
