### ISSUE TITLE
Language standards for code (US spelling vs. UK spelling)

### ISSUE THREAD

**Issue by MikeSmithEU** [ebu/benchmarkstt#12]
Up until now I've mostly been using UK spelling in code examples. What is the preference here, do we want to use UK spelling since this is mostly a European project (i.e. "normalisation", "colour") or do we want to use US spelling as is more widely used in open source projects (i.e. "normalization", "color")?

**Comment by amessina71** [comment]
I would go for UK spelling.

**Comment by EyalLavi** [comment]
I vote US for two reasons, both related to this being an open source project:
- Developers are more familiar with US spelling, which is a convention.
- Contributors may come from many countries and US spelling is more common outside Europe.

**Comment by MikeSmithEU** [comment]
Mostly neutral about it. Found myself having to self-correct a bit, it seems after years of programming I have US-spelling in my fingers (or maybe I just love the letter 'z').

**Comment by EyalLavi** [comment]
Agreed to use US spelling in Webex today. This applies to code and technical documentation only, not general documentation and normalization rules. However we will aim to be consistent across code and other resources. In any case, we must not have mixed spellings in the same document.
