### ISSUE TITLE
Edit Distance documentation

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#120]
Pypi doesn't include much info about the library used for the Levenshtein distance. Add a link to the github repo: https://github.com/aflc/editdistance

**Comment by EyalLavi** [comment]
Also add to the tutorial.

**Comment by EyalLavi** [comment]
Link to the repo is included in the code: https://github.com/ebu/benchmarkstt/blob/a372f30ce9b4f372a772482a0e4c482a1748336a/src/benchmarkstt/metrics/core.py#L96

**Comment by aro-max** [comment]
Add a precision about the Levenshtein distance. Generally speaking, it is defined at the character level. In the context of WER it is at the word level.

[Mode: 'levenshtein'] In the context of WER, Levenshtein distance is the
    minimum edit distance computed at the word level. This implementation uses the
    Editdistance, c++ implementation by Hiroyuki Tanaka:
    https://github.com/aflc/editdistance.
    See: https://en.wikipedia.org/wiki/Levenshtein_distance
