### ISSUE TITLE
Tests failing on fresh install

### ISSUE THREAD

**Issue by danielthepope** [ebu/benchmarkstt#130]
On a completely fresh install, i.e.
```
git clone git@github.com:ebu/benchmarkstt.git
cd benchmarkstt
python3 -m venv venv
source venv/bin/activate
make dev
```
We are unable to run the unit tests with `make test`, because a file `src/benchmarkstt/__meta__.py` doesn't exist at this point in time.

This metadata file is created when you run any `python setup.py` tasks, e.g. `python setup.py sdist bdist_wheel`, `python setup.py check` or even just `python setup.py` (which will return a failure but it will be enough to create that meta file).

There are a couple of possible solutions:
- Run a `setup.py` task within the `make dev` step
- Move the code that creates `__meta__.py` to somewhere that runs when you run `pip install ".[test]"`
- Something else?

What do you think?

**Comment by EyalLavi** [comment]
As far as I understand, `setup.py` is required for distribution through a package manager, and so `__meta__.py` would also be required for pypi. But we'd like the test to work for a dev install, so this rules out option 2.

What are the implications of running `setup.py`?

**Comment by EyalLavi** [comment]
For reference, the contents of `__meta__.py`:

```
# Automatically created. DO NOT EDIT
__version__ = '1.0'
__author__ = 'EBU'
```

**Comment by aro-max** [comment]
I agree with solution 2, this involves some changes in the Makefile as to run "make test" it is required to run "make dev" first.
- line 3 of the Makefile can be changed to: "test : dev"
- line  29 of Makefile : 
	change: python -m pip install --user --upgrade twine
	to:          python -m pip install --upgrade twine
  in a virtual environment, the --user option can generate an error.

**Comment by MikeSmithEU** [comment]
Solved with 

```Makefile
PYTHON:=$(shell test -e env/bin/activate && echo "env/bin/python" || echo "python3")
```

This assures the correct python to be used in the Makefile, while still allowing for non-`venv` setups

**Comment by MikeSmithEU** [comment]
> On a completely fresh install, i.e.
> 
> ```
> git clone git@github.com:ebu/benchmarkstt.git
> cd benchmarkstt
> python3 -m venv venv
> ```

^^ Should be `python3 -m venv env` btw

> ```
> source venv/bin/activate
> make dev
> ```
