### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by heenaI** [ebu/benchmarkstt#131]
Hi,
How many languages does the tool support?

**Comment by EyalLavi** [comment]
The tool is language agnostic. It compares the reference and hypothesis without an understanding of the language used. It was used successfully on Arabic and Russian as well as Latin scripts.

**Comment by heenaI** [comment]
Hi Eyal, Thank you for your reply. Another question regarding the definition of Refrence and Hypothesis text. I have two two texts Human transcribed and ASR. I want to evaluate ASR based on human transcribed, so I am right in thinking that Human transcribed would be reference and hypothesis is ASR??

**Comment by heenaI** [comment]
I will test the tool with Hindi and report back the results

**Comment by EyalLavi** [comment]
Hi Heenal, you are correct: reference = ground truth = human transcript. We'd love your feedback on the tool. Please raise an issue here with any bug/suggestions.
