### ISSUE TITLE
Character Error Rate (CER)

### ISSUE THREAD

**Issue by cjrosen** [ebu/benchmarkstt#132]
At Swedish Radio we've been discussing the benefits of being able to benchmark CER (character error rate). We think it might be good for getting an idea about if a particular (homegrown or other) ASR model are good at getting the characters right, but may be lacking in grammar (language model)?
It would be interesting too to se how it compare to WER for vendors, since it might indicate how large part of the token errors are due just to a single or a couple of characters being wrong, like endings or odd spelling of names.

Anybody else been thinking about this? I'm thinking about branching and implement this if you don't mind. Please post ideas here, and we can get the algorithm and format right. My basic idea is to create a `--cer` option parallel to `--wer`. Then simply remova any non-interesting chars by regex and do `levenshtein`-distance on the whole string, and skip the tokenization step. I believe whitespaces should normally be removed for such a metric, but I think it should be up to the user to say so via regex input.

Let me know if you have any thoughts!

**Comment by aro-max** [comment]
Thanks for this proposal Carl-Johan. I definitely support this idea to have both options, WER and CER in the tool. About, the Levenshtein distance on the whole string you mentioned. Don't you think it could be interesting to have the Levenshtein distance on Substitutions only? This will allow to have a score easy to understand.

**Comment by cjrosen** [comment]
Yes, I've been thinking about that too, Alexandre! Would be interesting to do a quick test to see if such a more nuanced error would help understand if the quality of the transcript is good enough for certain purposes. I guess the implementation if it is quite straight-forward, but finding ways to evaluate its meaning could be more difficult.

**Comment by cjrosen** [comment]
Hi,
To implement a ```--cer``` (character error rate) metric, we would need to be able to segment the text differently. As a list of characters, instead of as a list of words. I'm a little lost in the structure of the project, but it seems the [```PlainText``` class](https://github.com/ebu/benchmarkstt/blob/master/src/benchmarkstt/input/core.py#L15) is responsible for splitting a text into a list of tokens based on the provided ```segmenter```argument. At the moment it seems to always default to splitting texts by whitespaces (via the [```Simple``` segmenter](https://github.com/ebu/benchmarkstt/blob/master/src/benchmarkstt/segmentation/core.py#L10)'s default ```pattern```), which is good for word error rate, but I would like to create a new segmenter (possibly called ```Character```, or something)  and make it the default if the requested metric is ```--cer```. Or would we rather pass a different pattern to ```Simple``` segmenter if the metric is ```--cer```?

Or turning it around: Is there a way to pass the segmenter regex pattern into the command? Could i default that pattern to something splitting the text in characters (or not splitting the text at all) at a higher level of the call chain? Even if it's possible to pass the segmentation pattern with the command, we don't want the user to have to specify a pattern when calling the ```--cer``` metric, since the default whitespace segmentation doesn't make sense for character error rate. 

I feel unsure how/where to implement this check for metric. It seems to me it needs to be implemented at several positions to handle calls from API, CLI/plaintext and CLI/file. In the case of choosing a segmenter for a CLI/file input, we'd need to know the requested metric inside the [```File``` class](https://github.com/ebu/benchmarkstt/blob/master/src/benchmarkstt/input/core.py#L43), where the ```PlainText``` segmenter is now selected by default if the file extension is ```txt``` regardless of the metric.

Any thoughts on these thoughts would be helpful!

**Comment by cjrosen** [comment]
Regarding the previous entry: I've gone ahead and implemented a CER metric that ignores whitespaces, for now.
