### ISSUE TITLE
Code review and merge procedure

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#15]
A discussion point for next meeting.

**Comment by MikeSmithEU** [comment]
I propose having a develop branch and a master branch.
Releases are tagged in the master branch, every merge from develop into master causes a new (minor) release.
Development is done on our own branches (based off master), then merged and tested into develop. Minor bugfixes can be done directly on develop (and if needed cherry-picked to master).

As such, develop should *never* be behind master.

**Comment by MikeSmithEU** [comment]
In the end I propose pretty much this: https://nvie.com/posts/a-successful-git-branching-model/

![](https://nvie.com/img/git-model@2x.png)

It is pretty much used standard for most major projects, and have seen it working well myself.

**Comment by EyalLavi** [comment]
Agreed today that the general idea is okay but to keep it open so that we develop a process that suits us.

**Comment by ghost** [comment]
Once we've decided on what to do here we will need to update `docs/CONTRIBUTING.rst`.

Comment from @EyalLavi on `CONTRIBUTING.rst`:
> Should we mandate that a branch must correspond to an issue? This will make tracing decisions easier.

**Comment by EyalLavi** [comment]
Agreed today.
