### ISSUE TITLE
Add WER based on minimal edit distance (Levenshtein distance)?

### ISSUE THREAD

**Issue by johann-petrak** [ebu/benchmarkstt#163]
It would be very useful to allow the use of Levenshtein edits instead of the difflib edits. 

This would allow to calculate "proper" wer and also other metrics like match error rate or word information lost correctly, and still use them to also show the differences etc.

**Comment by aro-max** [comment]
You can use the Levenstein distance instead of difflib edits which is the default parameter. Please see the explanation in the doc :
https://benchmarkstt.readthedocs.io/en/latest/tutorial.html#word-error-rate-variants

**Comment by aro-max** [comment]
The doc explains how to use the Levenshtein distance.
