### ISSUE TITLE
Project toolkit name

### ISSUE THREAD

**Issue by MikeSmithEU** [ebu/benchmarkstt#17]
We have to decide on how to name the toolkit. An easily identifiable name stands out of the pack and seems to encourage usage.

At the moment I've just chosen a name for #16 that seemed perfectly adequate: "conferatur". I've chosen this because the latin meaning seems to apply decently to this project and that could be easily search/replaced if we go with another name.

See: https://en.wiktionary.org/wiki/confero#Latin

On one hand it means "to bring together", "to unite", "to consult" as is easily identifiable from the verb "to confer" which is based on it. This is what we are attempting to do with this project, to create something through cooperation of interested parties that will be useful to all.
On the other hand it means "to set in opposition, oppose, match", which is what the toolkit itself is trying to do, namely to compare different solutions by matching them through common metrics.

The name is not set in stone, and may be changed at any time, but I propose once we've decided on it to rename the git repository name to this as to keep things consistent.

**Comment by EyalLavi** [comment]
Agreed today to discuss on Slack and then vote.

**Comment by EyalLavi** [comment]
Suggestion today: benchmark-stt, ebu-stt. Decision is only required for the first release.

**Comment by MikeSmithEU** [comment]
Decision has been made, name will be 'BenchmarkSTT', python package named 'benchmarkstt'.
