### ISSUE TITLE
Code reviewers

### ISSUE THREAD

**Issue by MikeSmithEU** [ebu/benchmarkstt#23]
Call to arms for all willing and able code reviewers. We need each other to double check proposed work every Pull Requests as well as make meaningful suggestions and ask the right questions.

Those who feel the calling, please let it be known here, as well as possibly where the major area of expertise is (some may be excellent in checking the frontend while others may be more attuned to backend or testing stuff).

Also see #14 #15 #21

**Comment by MikeSmithEU** [comment]
Current code reviewers are @EyalLavi @danpope-bbc and @MikeSmithEU

**Comment by EyalLavi** [comment]
Reviewers are @danielthepope  annd @EyalLavi but anyone is welcome to raise issues.
