### ISSUE TITLE
Hosting of documentation and website (currently just the JSON-RPC api "explorer")

### ISSUE THREAD

**Issue by MikeSmithEU** [ebu/benchmarkstt#24]
Currently we have the documentation hosted from my own repository on github pages, available at https://conferatur.mikesmith.eu 
Do we want to maintain this as github pages, but under the account of EBU, or do we want to push this to readthedocs.org (again, using an ebu account).

Similarly can EBU provide us with a location to make e.g. the API JSON-RPC api explorer available? (currently made available at https://conferatur.viaa.be/api and hosted by VIAA).

**Comment by EyalLavi** [comment]
@MikeSmithEU why not simply include it as part of the repo? It took us about five minutes to run it locally with Docker so that's possibly good enough for now. It also guarantees that when a user uses the toolkit, they test their actual rules rather than the hosted instance's.

**Comment by MikeSmithEU** [comment]
Always good for showing off an app’s capabilities. Currently it’s there for group members to be able to quickly check the newest versions while thinking up normalisation rules.

**Comment by MikeSmithEU** [comment]
No JSON-RPC api will be publicly available through ebu hosting, #83 is new place to discuss where we will place the documentation...
