### ISSUE TITLE
Publishing on pypi

### ISSUE THREAD

**Issue by MikeSmithEU** [ebu/benchmarkstt#25]
To make the code easily available and installable we should probably publish the package on pypi.org 

Everything is set up to already support this, once the name is decided (see #17 ) . We should publish this with an account of ebu probably, does this already exist?

**Comment by EyalLavi** [comment]
@JPEvain does the EBU have an account so that we can publish under the EBU? It would help if there was more than one administrator in the EBU. Once it's published, how do code maintainers publish on pypi? Doing this will prevent another package with our name.

**Comment by JPEvain** [comment]
Creating an account / project on pypi is not difficult. We would need to create one to further investigate the flexibility in management, number of admin, etc. But colleagues say it can be quite fexible.

**Comment by EyalLavi** [comment]
@JPEvain confirmed in meeting today. Suggestion is to wait for release 1 for publishing but for EBU to create the account so that we can publish quickly.

**Comment by MikeSmithEU** [comment]
Once EBU account has been created and benchmarkstt repository is added, at https://pypi.org/manage/project/benchmarkstt/collaboration/ you can then add maintainer 
"MikeSmithEU". I can then push builds to PyPi.

**Comment by aro-max** [comment]
EBU account created
