### ISSUE TITLE
Language code

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#26]
Normalization rules and other resources will be organised by language codes, including country variants. 

ISO 639-3 defines 3-letter codes: `eng` 
AWS and GCP use 2-letter codes (ISO 639-1?) followed by country codes: `en-US | es-US | en-AU | fr-CA | en-GB`

Do we want to conform to existing vendor practice or use a combination of both, for example `eng-GB`?

**Comment by EyalLavi** [comment]
Perhaps we don't have to be prescriptive about files being named with language codes? Continue discussion on Slack.

**Comment by pietrop** [comment]
I think it would make sense to use the current vendor practices. Unless there strong arguments against.

**Comment by MikeSmithEU** [comment]
I propose fulllocale to follow https://tools.ietf.org/html/bcp47 . This would support all languages and script variations, while offering decent fallback (we would follow standard L10N practises) E.g. these files could both exist: `nl.csv`, `nl-BE.csv`.

We could then select the most specifically appropriate locale automatically e.g., if text is in nl-NL `nl.csv` would be used. This would also allow us to support separation per script, eg `zh-Hant-CN` would be `Chinese (Traditional, China)` and available locale solutions can then go find the most appropriate replacement file for that locale (i.e. we support a lot of separation, while not introducing our own complexity and using a well established standard).

Or to use a European example: `sr-Latn` for Serbian (Latin) and `sr-Cyrl` for Serbian (Cyrillic).

This is forward compatible for "exceptional" languages, as well as following the AWS and GCP convention (which seems to be based on BCP 47 as well). 

@EyalLavi FYI the first language code is ISO 639-1 ISO 639-2/T and 639-3 and 639-5 in that order of lookup (and with a preference to use 639-1 2-letter codes if available for that language).

**Comment by EyalLavi** [comment]
BCP47 sounds like a good idea. My only concern is that if we don't use the same system that's used by vendors, we will have to build additional logic to resolve BCP47 codes to vendor codes. It might be trivial though.  

BTW, only European languages are in scope for this tool: https://github.com/ebu/ai-benchmarking-stt/tree/master/docs/releases/1.0

Options: 
1. Adopt BCP47 as @MikeSmithEU suggests. Pros: future proof, extensive, standards compliant. Cons: additional complexity, less user friendly, possibly out of scope.  
2. Use vendors codes. Pros: easy option, user friendly. Cons: dependency on vendors code, not future proof.
3. Defer decision to future release and use vendor codes for now.

**Comment by pietrop** [comment]
Some vendors, like [google](https://cloud.google.com/speech-to-text/docs/languages) use `BCP-47`  might be useful to review what other vendors use?

**Comment by EyalLavi** [comment]
A library already exists for translation from full BCP47 to the subset of two-letter language code followed by two-letter country case. The decision is to use BCP47 without further restriction on the format.
