### ISSUE TITLE
Define and document WER algorithm

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#31]
This algorithm uses the results of the diff algorithm (#30) to calculate Word Error Rate. 

In the documentation, provide pseudo-code and discuss the approach (linking to an issue could be a good alternative).

**Comment by MikeSmithEU** [comment]
I would link to https://en.wikipedia.org/wiki/Word_error_rate and document that we use equal weights for all of insertions, deletions and substitutions.

Pseude-code shouldn't be necessary, only the formula:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/7db6226f0c365982b94f221d68530bf8a6a50611)

What should be well documented is the diff algorithm (see #30 ).

**Comment by EyalLavi** [comment]
Sounds good. The page seems to be still active, so the link should be a permalink to the current version e.g. https://en.wikipedia.org/w/index.php?title=Word_error_rate&oldid=888037079

**Comment by MikeSmithEU** [comment]
We should add basic documentation and the formula to the documentation, and indeed link to the wiki for more info, not sure if we need the permalink to the current version, but have no objections...
