### ISSUE TITLE
Clarify status of JSON-RPC api explorer

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#35]
This is a very useful tool, but since it is not in scope for v1 we should make sure it doesn't take too much time. It was decided in the meeting today that this will provided as-is, without any tests or code reviews. This issue is to add a note to this effect to the documentation.

**Comment by MikeSmithEU** [comment]
Documentation is updated @EyalLavi and part of #48 Propose closing this issue after you check if the warning at https://benchmarkstt.mikesmith.eu/api.html is ok for you.
