### ISSUE TITLE
Handling multiple files for normalization rules 

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#46]
There are three types of normalization rules, _per language_:
- Default. This is a set of built-in rules if none are specified
- Simple pair replacements
- Regex replacements

Each one of these types can include more than one physical file, for example:
```
/en-GB/regex_file_1
/en-GB/regex_file_2
/en-GB/pairs_file_1
/en-GB/pairs_file_2
```
Each one of these files can contain multiple rules. The order in which the rules are applied is important, so we need to clarify - 
- In what order files are processed
- In what order rules within each file are processed.

@MikeSmithEU 's suggestion is to pass the normalization rule files in a config file, like  `--normalization configfile myownconfigfile.conf`

Then, inside `myownconfigfile.conf`, the user lists the files to use. The rules files will be processed in the same order as they appear in the config file. The rules within each file will be processed in their order in the file.

If  no `--normalization` parameter is given it would be equivalent to something like `--normalization configfile ./resources/normalization/default/en_GB`.

Questions:
- What happens when the user specifies a language but no default file exists for that language - still use the English?
- Would it be clearer to the user (and easier to maintain) if instead of creating default files, we ship the code with some basic files in the language folder? This means that if the user doesn't use the config, no normalization takes place at all. I like this because it removes 'magic' and makes the behaviour very transparent.

**Comment by MikeSmithEU** [comment]
> What happens when the user specifies a language but no default file exists for that language - still use the English?

This is to be decided what the action should be, however we should already issue at least a warning in this case and inform the user which fallback option is being used.

> Would it be clearer to the user (and easier to maintain) if instead of creating default files, we ship the code with some basic files in the language folder? This means that if the user doesn't use the config, no normalization takes place at all. I like this because it removes 'magic' and makes the behaviour very transparent.

Seems like a good idea indeed, in practise this means the "default" normalization is a "null"-normalization, i.e. it does nothing. Implementation wise, this default behaviour can be easily switched as the project goes on. 

Alternatively, if no language is specified, no normalization is done (if none is specified by the user), while if a language is specified it would load the 'default' normalization rules available for that language (again, if none is specified by the user). To me this seems the best of both worlds, if no default normalization is loaded when providing a language, I'm unsure what the purpose of even passing a language argument is... In essence, providing a language is short hand for 'load the most appropriate default normalization rules for my language automatically'...

**Comment by MikeSmithEU** [comment]
(Relates to #47, this decision might impact requiring language code)

**Comment by EyalLavi** [comment]
There may be a good reason for not specifying a language but still provide normalization rules. For example, if the test contains a conversation in 2 languages and the STT engine supports automatic identification of the language. In this case the user may want to combine normalization rules for two languages, as a single file or as two files. 

For this reason, and also to work around creating logic for resolving languages and normalization rules, we could do away with any internal logic and make the user specify the normalization rules explicitly. For example: 

`benchmarkstt --reference ref.txt --hypothesis hyp.txt --metric wer --lan en-GB  --rules ~/rules/`

Both `lan` and `rules` are optional. We then have these scenarios: 

1. `lan` and `rules` both specified: the language code is passed to the vendor, normalization applied as specified.  
2. `lan` omitted, `rules` present: If the vendor requires language then the toolkit will surface the error to the user. Normalization applied as specified. Warning is issued.
3. `lan` present, `rules` omitted: no normalization takes place. Warning is issued.
4. `lan` and `rules` both omitted: no language passed, no normalization takes place. Warning issued. 

Note that `rules` takes a location, not a series of files, so no change is required to the code that handles the order of processing.

**Comment by EyalLavi** [comment]
Discussion today: better to separate normalization rule files used from their location by using a file that lists the normalization files:   
`benchmarkstt --reference ref.txt --hypothesis hyp.txt --metric wer --lan en-GB --rules ~/rules.txt`

`rules.txt` can look like this:
```
~/en-GB.csv
~/all-languages/numbers.csv
~/any-location/any-file.csv
```

**Comment by EyalLavi** [comment]
@MikeSmithEU wrote up a useful list of options with pros and cons: https://benchmarkstt.mikesmith.eu/proposals/benchmark-flow.html. Based on that, I think the best approach would be to use a config file, which for this release will include links to normalization rule files only. 

`benchmarkstt --reference ref.txt --hypothesis hyp.txt --metric wer --lan en-GB --conf config`

The `config` file contains sections. For this release, the only section is normalization:

```
# content of config

[normalization]
pairs ~/path-to-pairs-rules-file/pair1.csv
regex ~/path-to-regex-rules-file/regex1.csv
```
In future release, other sections can be added for more complex use cases. 

We also have some readily available normalization rules that can be used from the command line. The suggestion is to avoid a mixed model and state that all rules must be specified explicitly in config. This is to minimize user confusion, documentation overhead and testing. This means that although `--lowercase` is available, the preferred approach would be to include a path to a file containing a regex replacement rule in `conf`. We will not write tests for CLI normalization rules.

**Comment by MikeSmithEU** [comment]
Would prefer `--config` and `-c` to `--conf`, this small extra verbosity is in line with the `--reference` and `-r` arguments instead of the `--ref`.

**Comment by MikeSmithEU** [comment]
> We also have some readily available normalization rules that can be used from the command line. The suggestion is to avoid a mixed model and state that all rules must be specified explicitly in config. This is to minimize user confusion, documentation overhead and testing. This means that although `--lowercase` is available, the preferred approach would be to include a path to a file containing a regex replacement rule in `conf`. We will not write tests for CLI normalization rules.

In my mind CLI normalization rules, as available through `benchmarkstt --normalization`, are exactly the same ones that the config has available. We can decide on the best name for each rules, (eg. `pairs` instead of the current `replace`, and `regex` instead of the current `regexreplace`, which both are fine by me), but I prefer that level of consistency which adds clarity for the user.

`lowercase` would thus also be available by default in the config, eg. 
```
[normalization]
lowercase
pairs ~/path-to-pairs-rules-file/pair1.csv
regex ~/path-to-regex-rules-file/regex1.csv
```

A separate discussion needs to be had about which normalizers should be supported.

**Comment by danielthepope** [comment]
I think it would be a good idea to define your config file as a specific file type: that way you don't need to write your own parser. A YAML file might give the required flexibility:

`en-GB.yaml`
```yaml
normalization:
  - lowercase
  - pairs ./rules/pair1.csv
  - pairs ./rules/pair2.csv
  - regex ./rules/regex1.csv
```
This way, you can specify multiple pairs files if you want because the rules will just be read as an ordered list of strings.

Also, having normalization rules applied from the command line such as `--lowercase` should still be supported, since they'll be the easiest way to get started with the tool. If both a config file and extra normalization flags are specified, `benchmarkstt` should be clear in what it does, both in the program output and the documentation. Perhaps always apply CLI normalization rules after rules specified by the config file, and be clear that that's what it does.

**Comment by danielthepope** [comment]
Also, even though it looks like we've stepped away from the idea already, I'd like to discourage the use of specifying whole folders full of rule definition files when using the `--config` flag. I'd prefer to see a default config file for a given language e.g. `en-GB.yaml` which defines a set of rules for that language. If a user wants to apply a different set of rules, they can define their own config file and point the CLI to that file instead.

**Comment by MikeSmithEU** [comment]
> I think it would be a good idea to define your config file as a specific file type: that way you don't need to write your own parser. A YAML file might give the required flexibility:

The purpose of the own config file parser (already done btw, but that should not influence the decision) was to simplify the config format. A yaml file is certainly possible but complicates the format further imho (e.g. mistakes with indentation are not uncommon for non-technical people).
Certainly up for discussion though.

> This way, you can specify multiple pairs files if you want because the rules will just be read as an ordered list of strings.

With my previously proposed config file this is also the case. Am unsure if this remark was meant to convey an added advantage or simply to explain the above yaml config you added?

> Also, having normalization rules applied from the command line such as --lowercase should still be supported, since they'll be the easiest way to get started with the tool. If both a config file and extra normalization flags are specified, benchmarkstt should be clear in what it does, both in the program output and the documentation. 

Agreed

> Perhaps always apply CLI normalization rules after rules specified by the config file, and be clear that that's what it does.

I would simple follow the order of the command line arguments. To me it makes more sense that the following command:

```
benchmarkstt --lowercase --config conf-file --regexreplace "hello" "world"
```

should apply the lowercase first, then the config file (and the rules contained within it) and then the regexreplace...

In the documentation we would then specify that normalization rules are applied in the order they are provided (i.e. for command line, from left to right, and for a config file from top to bottom).

**Comment by EyalLavi** [comment]
Decision in meeting today: 
- The config file approach was agreed. In this release, the config file will support a `[normalization]` section only.
- We will support a mixture of CLI and config file. When mixed, they will be processed in the order in which they are specified, as @MikeSmithEU suggested above.
- The format of the config file will be the native one. YAML (or similar) may be added later.  
- There will be no default config. If the user does not specify normalization rules, no normalization will take place.

**Comment by EyalLavi** [comment]
Keeping this issue open until this feature is released.

**Comment by EyalLavi** [comment]
Implemented in RC1.
