### ISSUE TITLE
Make language code(s) mandatory?

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#47]
For: 
- without language code we can't determine normalization rules 

Against: 
- some vendors support automatic language identification
- future support for mixed-language benchmarking

**Comment by MikeSmithEU** [comment]
Against for the main reason that it would allow for easier customisation and extension. Making it required adds unnecessary restrictions.

**Comment by MikeSmithEU** [comment]
Arguments 'against' according to the principles (ref. https://github.com/ebu/ai-benchmarking-stt/wiki/Principles):

- Usability over completeness: adding a required argument adds a restriction lowering usability
- Pragmatism: "We want to deliver maximum benefit with minimal effort, incrementally" seems quite applicable as well
- Specific over generic: "It's better to benchmark for your own use-case than attempt to capture all scenarios in a single test set." Some specific use-cases could be excluded if a language is made mandatory.

**Comment by EyalLavi** [comment]
Agreed in meeting today to make language code optional and emit a log warning when it is not provided by the user.
