### ISSUE TITLE
Organisation of resources/languages

### ISSUE THREAD

**Issue by amessina71** [ebu/benchmarkstt#5]
Should we organise around languages or resource types? E.g.:

it_it/stopwords
en_uk/stopwords

or 

stopwords
   |
   -- it_it
   -- en_uk

**Comment by pietrop** [comment]
I would suggest to organise it around resources

**Comment by MikeSmithEU** [comment]
+1 for organising around resources, as this would more transparently allow per-resource optimal locale selection.

Eg. if nl_be does not exist, we should check if any other nl_* exists (eg. nl_nl). To do this check for each resource we would need to check if the resource file exists in each directory anyways on a per-resource basis. This could be easily overlooked if we think all resources are in the same folder by definition (which would seem implied if we organise per language) for any given language, while a valuable fallback option might be available.

**Comment by EyalLavi** [comment]
+1 for resources, but it's worth noting here that this organisation will make it tricky for users to see at a glance if their language is fully supported. Just a point to remember and to consider when documenting.

**Comment by MikeSmithEU** [comment]
Proposal in PR #19 also favours the per-resources structure

**Comment by EyalLavi** [comment]
Agreed to organise by resource in Webex 2019-02-05.
