### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by MikeSmithEU** [ebu/benchmarkstt#50]
Refs: #17

Should we rename the repository name `ai-benchmarking-stt` to `benchmarkstt` to be more in line with the actual toolkit name? If we want this it is best to do this as soon as possible. 
I would propose to do this immediately after the merge of #48 PR2, the following Pull Request will then update the repository documentation to reflect this change.

My vote: 👍

**Comment by EyalLavi** [comment]
I'm in favour, but before we do this let's make sure everybody is aware that they should update their local clone. According to [this](https://help.github.com/en/articles/renaming-a-repository), project pages URL are _not_ redirected. I'm not sure if that means they will break, but it won't be difficult to recreate this project page if it breaks.

**Comment by EyalLavi** [comment]
This is done so closing the ticket.
