### ISSUE TITLE
Add simple flow based on current normalizers and metrics

### ISSUE THREAD

**Issue by MikeSmithEU** [ebu/benchmarkstt#53]
I.e. a command that does:

```
normalization -> segmentation -> metrics
```

**Comment by EyalLavi** [comment]
Additional context: 

first big pull request was implementing normalization features (i.e. all the Normalizer classes), they were already accesible via the api and cli eg.
```
$> echo "TEST" | benchmarkstt normalization --lowercase
test
```

second big pull request (PR2) was the implementation of Schema structure, segmentation and metrics (eg. WER). These have also been exposed through jsonrpc api and commend line, eg.
```
$> benchmarkstt metrics -r kw57d2qg08.reference.txt -h kw57d2qg08.hypothesis.txt --wer --diffcounts             
wer
===
0.010254

diffcounts
==========
OpcodeCounts(equal=5695, replace=53, insert=0, delete=6)
```

now these two have been combined into a "flow", eg.
```
$> benchmarkstt flow -r kw57d2qg08.reference.txt -h kw57d2qg08.hypothesis.txt --lowercase --wer --diffcounts
wer
===
0.010080

diffcounts
==========
OpcodeCounts(equal=5696, replace=52, insert=0, delete=6)
```

**Comment by EyalLavi** [comment]
Agreed in meeting today:
- Create `benchmarkstt-tools` for the current subcommands.
- `benchmarkstt` without any subcommand will be the equivalent of current `flow`.

Keeping this issue open until this feature is implemented.

**Comment by EyalLavi** [comment]
Implemented in RC1.
