### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by MikeSmithEU** [ebu/benchmarkstt#55]
I propose following PEP 0440 for this:

https://www.python.org/dev/peps/pep-0440/

In short this would mean version numbers like this:

```
X.YaN   # Alpha release
X.YbN   # Beta release
X.YrcN  # Release Candidate
X.Y     # Final release
```

Our current tagged pre-release version, as tagged in github, is `0.0.2`, this should be `0.0a2` to indicate the pre-release status (the next pull request - another pre-release - I propose tagging as `0.0a3`.

**Comment by EyalLavi** [comment]
Agreed today to use 3-level semantic versioning in PEP 0440. For version 1 we will have:
`1.0rc0`  // release candidate
`1.0rc1` // bug fix version
`1.0.0` // official release
