### ISSUE TITLE
Command line help output

### ISSUE THREAD

**Issue by amessina71** [ebu/benchmarkstt#60]
After installing the tool, running benchmarking --help gives an incomplete helper text (see below). At least info on how to build the basic cmdline for the available modules should be added.

dlvideo@dlstation1:~/benchmarkstt$ benchmarkstt --help
usage: benchmarkstt [--help]
                    [--log-level {warn,error,warning,debug,critical,info,notset}]
                    [--version]
                    {normalization,metrics} ...

BenchmarkSTT main command line script

positional arguments:
  {normalization,metrics}

optional arguments:
  --help                show this help message and exit
  --log-level {warn,error,warning,debug,critical,info,notset}
                        set the logging output level
  --version             output benchmarkstt version number

**Comment by MikeSmithEU** [comment]
I've been looking at setting the default subcommand to 'flow' (or 'benchmark', which might be a more clear name, tbd). However then it becomes unclear that multiple commands are available (i.e. the `api`, `normalization` and `metrics`, and further confuses the issue.

At the same time I want to avoid removing support for using the submodules separately (which would only further complicate the entire command when other stuff than the 'most-frequently-used' command is wanted).

Therefore I propose not having a default subcommand, but instead properly documenting the `benchmarkstt --help` functionality to state that each subcommand has its own help, and a description as to what each subcommand is meant to do.

I will try and add additional help already.

**Comment by amessina71** [comment]
ok. What about something like "benchmarkstt \<modulename\> --help " to disclose each of the available modules' parameters?

**Comment by EyalLavi** [comment]
Following #53, help should include a reference to `benchmarkstt-tools` and list the supported parameters for `benchmarkstt`

**Comment by EyalLavi** [comment]
Implemented in RC1.
