### ISSUE TITLE
Post-processing normalisation 

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#7]
An idea for a different approach to normalisation rules: rather than define them in advance, build an interface where the user can mark replacements that are effectively the same. For example, if the ASR result has `we're` and the reference has `we are`, the user can click this word pair. When the user does this, two things happen:
- The WER score is updated
- A new replacement pair is added to the normalisation table. 

In this way we 'crowd source' the normalisation and avoid building complex normalisation rules.

**Comment by MikeSmithEU** [comment]
This seems like a purely GUI/frontend decision/suggestion, can we label or classify (milestone?) these issues as we are currently not in that phase yet?

**Comment by EyalLavi** [comment]
@MikeSmithEU I created this issue so it doesn't get forgotten. If we adopt this approach, we could reduce the number of normalisation rules. I'll create a 'backlog' release for these kinds of issues.
