### ISSUE TITLE
Add instructions for building the docs

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#71]
Mainly because I keep losing them!

**Comment by EyalLavi** [comment]
In root: `make docs`
Might have to do a `pip install -e '.[docs]'` for dependencies
Then after make docs, built docs are available in docs/build/html

**Comment by EyalLavi** [comment]
Only for local build. Add reference for publishing on readthedocs.com.

**Comment by MikeSmithEU** [comment]
Local build instructions:

```
pip install -r docs/requirements.txt
make docs
```
