### ISSUE TITLE
Replacement optional when normalizing

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#77]
What happens when no replacement string is given? It's counterintuitive that the replacement is optional when the purpose is to normalize the text. 

`[--regex search [replace]] [--replace search [replace]]`. 

If there's a good reason to search without replacing we should document this. Otherwise, I vote we make replacement sting mandatory.

**Comment by EyalLavi** [comment]
If replace argument not given it will be replaced with an empty string. @MikeSmithEU suggest to make replacement string mandatory, but support empty string "".

**Comment by MikeSmithEU** [comment]
See #101
