### ISSUE TITLE
Official release

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#82]
Tasks:
- [x] PyPi #25 
- [x] News item on EBU website
- [x] Technical article
- [x] Tutorial with files that we can add  
- [x] API and explorer tests and documentation
- [x] #113

**Comment by EyalLavi** [comment]
Next step: discuss the release with @danielthepope

**Comment by EyalLavi** [comment]
@alexandre-rouxel and @danielthepope to look at setting up actions to replace Azure pipelines.

**Comment by danielthepope** [comment]
I've investigated using GitHub Actions on my fork of benchmarkstt. So far it seems to have very similar functionality to Azure Pipelines so it would be good to move this project over.

How does this look to you? https://github.com/danielthepope/benchmarkstt/actions

And see what it looks like on a Pull Request: https://github.com/danielthepope/benchmarkstt/pull/1
