### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#83]
Keep versioned docs for each release. When the user is in one version, show them the docs for that version.

Not necessary for R1, but will be required for future releases.

**Comment by MikeSmithEU** [comment]
Proposal: use readthedocs.org for the documentation, it is capable of building the docs by itself (no further need for the `gh-pages` branch, nor the manual build ) and keeping multiple versions of the documentation.

Already tested a repository with multiple versions on readthedocs ( https://lump.readthedocs.io ) and this works great. To do the same using github pages would be a lot of unnecessary work.

This would require @JPEvain to create an ebu account on readthedocs.org

If someone from EBU can create the readthedocs account and add the repository, then under "Admin" -> "Maintainers" you can add "MikeSmithEU" and I will be able to do all necessary actions while EBU maintains control of the account...

This would completely remove the documentation build process as this would be done by tagging a version in github and clicking the "Build" button on readthedocs...

**Comment by EyalLavi** [comment]
Alexandre to create account.
Updates need to be triggered from readthedocs so contributors will need to login details.  
Add this step to the repo documentation and contribution guidelines.
