### ISSUE TITLE
Source text encoding

### ISSUE THREAD

**Issue by amessina71** [ebu/benchmarkstt#84]
The current release assumes UTF-8 encoding for the source text (both hyp and ref). However, depending on the process the text has gone through, this might not be always the case. I t could be good to add a way to specify the encoding of the sources and/or to force a re-format to a reference encoding (e.g. UTF-8) in case of problems.

**Comment by EyalLavi** [comment]
Requirement originated from vendors providing files in ISO-8859, or no information about the encoding. There's support for various encodings in Python. User will provide input encoding with an additional parameter. We will not attempt to guess the encoding. Output will always be UTF-8.

**Comment by MikeSmithEU** [comment]
To clarify “output will always be UTF-8”: output to screen is in the terminal encoding, which js most frequently UTF-8. Now added an environmental variable “DEFAULT_ENCODING” which makes all input and output files use that encoding. Setting specific encoding for some files (eg normalizer config files) is already possible, yet not properly documented, and that option might be missing in some places...
